Transform: AWS::Serverless-2016-10-31
Resources:
  SellRequests:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: material
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: material
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  CreateSellRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: CreateSellRequestFunction
      CodeUri: src/CreateSellRequest
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          TABLE_NAME: !Ref SellRequests
          TABLE_ARN: !GetAtt SellRequests.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SellRequests
      FunctionUrlConfig:
        AuthType: NONE
  CreateSellRequestFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${CreateSellRequestFunction}
Outputs:
  CreateSellRequestUrl:
    Value: !GetAtt CreateSellRequestFunctionUrl.FunctionUrl